# Generated by Django 5.2.14 on 2026-06-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-creado']},
        ),
        migrations.AddField(
            model_name='pedido',
            name='mesa_texto',
            field=models.CharField(blank=True, default='', help_text='Número de mesa', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nota',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('mesa', 'Comer aquí'), ('llevar', 'Para llevar')], default='mesa', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Recibido'), ('en_proceso', 'En preparación'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='nuevo', max_length=12),
        ),
    ]
