# Generated by Django 5.2.15 on 2026-06-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pedido_metodo_pago_pedido_propina_pedido_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, default='', help_text='WhatsApp del cliente para enviarle el ticket', max_length=20),
        ),
    ]
