# Generated by Django 5.2.15 on 2026-06-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_pedido_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Token opaco para el seguimiento público del pedido (no adivinable)', max_length=24),
        ),
    ]
