# Generated by Django 5.2.15 on 2026-06-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_pedido_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='eta_min',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo estimado de preparación en minutos (calculado al crear el pedido)'),
        ),
    ]
