# Generated by Django 5.2.14 on 2026-06-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='es_paquete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='etiqueta',
            field=models.CharField(blank=True, help_text="Ej. 'Favorito', 'Ligero', 'Nuevo'", max_length=40),
        ),
        migrations.AddField(
            model_name='item',
            name='incluye',
            field=models.JSONField(blank=True, default=list, help_text='["Café", "Pan dulce", ...]'),
        ),
    ]
