# Generated by Django 5.2.15 on 2026-06-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_es_paquete_item_etiqueta_item_incluye'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='limite_diario',
            field=models.PositiveIntegerField(blank=True, help_text='Máximo que se puede vender por día; null = sin límite', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tiempo_preparacion',
            field=models.PositiveIntegerField(blank=True, help_text='Minutos para preparar este platillo', null=True),
        ),
    ]
