# Generated by Django 5.2.14 on 2026-06-02 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(choices=[('menu', 'Menú'), ('catalogo', 'Catálogo de productos'), ('order_pay', 'Order & Pay'), ('reservas', 'Reservas'), ('fidelidad', 'Fidelización')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_addon', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=60)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='Subdominio: <slug>.tudominio.com', unique=True)),
                ('dominio_propio', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tipo_negocio', models.CharField(choices=[('restaurante', 'Restaurante'), ('tienda', 'Tienda / Comercio'), ('otro', 'Otro')], default='restaurante', max_length=20)),
                ('modo_vitrina', models.CharField(choices=[('menu', 'Solo Menú'), ('catalogo', 'Solo Catálogo'), ('ambos', 'Menú y Catálogo')], default='menu', max_length=10)),
                ('idioma_default', models.CharField(default='es', max_length=5)),
                ('idiomas', models.JSONField(blank=True, default=list, help_text='["es", "en"]')),
                ('activo', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='accounts.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('color_primario', models.CharField(default='#1F3864', max_length=7)),
                ('color_secundario', models.CharField(default='#2E75B6', max_length=7)),
                ('tipografia', models.CharField(default='Inter', max_length=60)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tema', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('prueba', 'Periodo de prueba'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], default='prueba', max_length=12)),
                ('inicia', models.DateField()),
                ('proximo_cobro', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('owner', 'Dueño'), ('staff', 'Personal')], default='owner', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='TenantModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('precio_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activado_en', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.modulo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'modulo')},
            },
        ),
    ]
