# Generated by Django 5.2.15 on 2026-06-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='num_mesas',
            field=models.PositiveIntegerField(default=0, help_text='Número de mesas del restaurante (para generar un QR por mesa)'),
        ),
    ]
