# Generated by Django 5.2.15 on 2026-06-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_num_mesas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='proximo_cobro',
            field=models.DateField(blank=True, help_text='Fecha del próximo cobro de la suscripción', null=True),
        ),
    ]
