# Generated by Django 5.2.15 on 2026-06-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenant_proximo_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='modulos',
            field=models.ManyToManyField(blank=True, related_name='planes', to='accounts.modulo'),
        ),
    ]
