# Generated by Django 5.2.15 on 2026-06-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_plan_modulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='clave',
            field=models.CharField(choices=[('menu', 'Menú'), ('catalogo', 'Catálogo de productos'), ('order_pay', 'Order & Pay'), ('reservas', 'Reservas'), ('fidelidad', 'Fidelización'), ('promociones', 'Promociones y cupones'), ('resenas', 'Reseñas y calificaciones'), ('whatsapp', 'Notificaciones WhatsApp'), ('reportes', 'Reportes y analítica'), ('inventario', 'Inventario y stock'), ('sucursales', 'Multi-sucursal')], max_length=20, unique=True),
        ),
    ]
