# Generated by Django 5.2.15 on 2026-06-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_modulo_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ciclo',
            field=models.CharField(choices=[('prueba', 'Prueba (3 meses)'), ('anual', 'Anual')], default='anual', max_length=10),
        ),
    ]
